# Generated by Django 4.1.7 on 2023-03-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('idNo', models.PositiveIntegerField()),
                ('courseName', models.CharField(max_length=50)),
                ('courseId', models.CharField(max_length=50)),
            ],
        ),
    ]
